# Generated by Django 5.1.6 on 2025-02-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bosqich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosqich', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Yuklangan fayl', upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Semestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Talim_yunalishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talim_yunalishi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Uquv_yili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uquv_yili', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SamDUkf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biletlar_soni', models.IntegerField(default=1, help_text='nechta bilet kerakligini kiriting?')),
                ('oson_savol', models.IntegerField(default=1, help_text='oson savollar')),
                ('urtacha_savol', models.IntegerField(default=1, help_text='urtacha darajali savollar')),
                ('murakkab1', models.IntegerField(default=1, help_text='murakkab1 darajaga mansub savollar')),
                ('murakkab2', models.IntegerField(default=1, help_text='murakkab2 darajaga mansub savollar')),
                ('qiyin_savol', models.IntegerField(default=1, help_text='eng qiyin savollar tuplami')),
                ('bosqich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bosqich')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fan')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file')),
                ('semestr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semestr')),
                ('talim_yunalishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.talim_yunalishi')),
                ('uquv_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uquv_yili')),
            ],
        ),
    ]
