# Generated by Django 5.1.3 on 2025-02-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', 'Oddiy'), ('murakkab1', 'Murakkab1'), ('murakkab2', 'Murakkab2'), ('hard', 'Qiyin')], max_length=10),
        ),
    ]
