# Generated by Django 5.1.3 on 2025-02-17 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamDUkf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2025)),
                ('semester', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('stage', models.IntegerField(default=0)),
                ('field_of_study', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='SamDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilet_number', models.IntegerField(default=5)),
                ('easy_question', models.IntegerField(default=1)),
                ('medium_question', models.IntegerField(default=1)),
                ('murakkab1_question', models.IntegerField(default=1)),
                ('murakkab2_question', models.IntegerField(default=1)),
                ('hard_question', models.IntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='main.samdukf')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_of_studies', to='main.samdukf')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='main.samdukf')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.samdukf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.samdukf')),
            ],
        ),
    ]
