# Generated by Django 5.1.3 on 2025-02-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_file_remove_samdu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdu',
            name='easy_question',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='samdu',
            name='hard_question',
            field=models.IntegerField(default=0),
        ),
    ]
