# Generated by Django 5.1.3 on 2025-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_samdu_easy_question_alter_samdu_hard_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdu',
            name='easy_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='samdu',
            name='hard_question',
            field=models.IntegerField(default=1),
        ),
    ]
