# Generated by Django 5.1.3 on 2025-02-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_samdu_easy_question_alter_samdu_hard_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
