# Generated by Django 5.1.3 on 2025-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdu',
            name='easy_question',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='samdu',
            name='medium_question',
            field=models.IntegerField(default=0),
        ),
    ]
