# Generated by Django 5.1.3 on 2025-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_samdu_easy_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Yuklangan fayl', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='samdukf',
            name='academic_year',
            field=models.IntegerField(default=2025, help_text='Akademik yil (masalan, 2025)'),
        ),
        migrations.AlterField(
            model_name='samdukf',
            name='field_of_study',
            field=models.CharField(help_text="Ta'lim yo'nalishi", max_length=55),
        ),
        migrations.AlterField(
            model_name='samdukf',
            name='semester',
            field=models.CharField(help_text="Semestr nomi (masalan, 'Bahor', 'Kuz')", max_length=10),
        ),
        migrations.AlterField(
            model_name='samdukf',
            name='stage',
            field=models.IntegerField(default=0, help_text='Bosqich (kurs) raqami'),
        ),
        migrations.AlterField(
            model_name='samdukf',
            name='subject',
            field=models.CharField(help_text='Fan nomi', max_length=200),
        ),
        migrations.DeleteModel(
            name='SamDU',
        ),
    ]
